version: '3'
services:
  backend:
    image: 'jtreaper/btarea4'
    container_name: "btarea4"
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: tarea3
    ports:
      - "8000:8000"